name: .NET

on:
  push:
    branches: [ feature/actions ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: test-${{matrix.os}}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        dotnet-version: [ '6.0.x' ]

    steps:
    - uses: actions/checkout@v2

    - name: Configure OS (if Linux)
      if: runner.os == 'Linux'
      run: sed -i 's/TLSv1.2/TLSv1.0/g' /etc/ssl/openssl.cnf
      shell: bash

    - name: Setup .NET ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal